.TH IMAGEPREP 1
.SH NAME
.B ImagePrepSharp
\- prepare digital photos for sharing on the Internet
.SH SYNOPSIS
.B "ImagaPrepSharp"
.SH DESCRIPTION
This is a simple (and hopefully user-friendly), GUI-based tool for
preparing digital photographs for sharing on the Internet. It resizes
the image file without distortion to the specified maximum dimension,
allows the user to rotate the image if needed, then saves the result as
a minimal JPEG or WebP file with no metadata.
.SH FILES
.TP
~/.imageprep/*
Various configuration and other cached data lives here.
